### ISSUE TITLE
Welcome message must be removed from index.html

### ISSUE THREAD

**Issue by RishabhJain2018** [ncs-jss/Nucleus#9]

**Comment by aka-jain** [comment]
If user is login then only it will shown there else only "Welcome" without name will be display.

**Comment by RishabhJain2018** [comment]
but it is also having login button in it.

**Comment by deshraj** [comment]
@RishabhJain2018 we will handle that using django templating.

**Comment by RishabhJain2018** [comment]
@DESHRAJ sure sir.

**Comment by aka-jain** [comment]
@RishabhJain2018 for now it just a dummy link only. After Backend integration we'll make it correct.

**Comment by RishabhJain2018** [comment]
@aka-jain sure sir. :+1:
